---
- name: Create Inventory
  template:
    src: "templates/inventory.j2"
    dest: "{{ output_dir }}/inventory"
  delegate_to: localhost

- name: copy over ansible.cfg
  copy:
    src: "templates/ansible.cfg"
    dest: "{{ output_dir }}/ansible.cfg"
  delegate_to: localhost

# - name: Copy Foreman Ansible modules
#   synchronize:
#     src: foreman-ansible-modules
#     dest: //localhost/{{ output_dir }}
#   delegate_to: localhost

- name: Copy Foreman Ansible modules
  unarchive:
    src: files/foreman-ansible-modules.tgz
    dest: "{{ output_dir }}"
  delegate_to: localhost
